name: Continuous Integration BaseModelica.jl

on:
  pull_request:
  push:
    branches:
      - master
    tags: '*'

jobs:
  unittest-testbasemodelica:
    name: GitHub Actions TestBaseModelica
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-version: [1.11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia
        uses: julia-actions/cache@v2

      - name: Build TestBaseModelica
        uses: julia-actions/julia-buildpkg@v1
        with:
          project: TestBaseModelica

      - name: Test TestBaseModelica
        uses: julia-actions/julia-runtest@v1
        with:
          project: TestBaseModelica

  test-mtk-import:
    name: GitHub Actions TestBaseModelica
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-version: [1.11]
        omc-version: [stable]
        python-version: ['3.12']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - name: Setup OpenModelica
        uses: OpenModelica/setup-openmodelica@v1
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            'omc'
          libraries: |
            'Modelica 4.0.0'
          omc-diff: true

      - name: Check if .CI/installLibraries.mos works
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            omc .CI/installLibraries.mos
          fi

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'            # caching pip dependencies
      - name: Install Python dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Run library test
        shell: bash
        run: |
          export MY_SANITY_CHECK_DIRECTORY=sanityCheck
          python test.py --branch="${{ matrix.omc-version }}" --basemodelica-mtk-import --noclean --verbose configs/sanityCheck.json

      - name: Generate HTML results
        shell: bash
        run: python report.py --branches="${{ matrix.omc-version }}" configs/sanityCheck.json

      - name: Zip HTML results
        shell: bash
        run: |
          python .github/scripts/archiveResults.py "MyLibrary" "1.0.0" "${{ matrix.omc-version }}" "html/"
