name: Continuous Integration BaseModelica.jl

on:
  pull_request:
  push:
    branches:
      - master
    tags: '*'

jobs:
  test:
    name: GitHub Actions TestBaseModelica
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-version: [1.11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia
        uses: julia-actions/cache@v2

      - name: Build TestBaseModelica
        uses: julia-actions/julia-buildpkg@v1
        with:
          project: TestBaseModelica

      - name: Test TestBaseModelica
        uses: julia-actions/julia-runtest@v1
        with:
          project: TestBaseModelica
